#!/usr/bin/python2

# Copyright (c) 2013 - Mathieu Bridon
#
# This application is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This application is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this application.  If not, see <http://www.gnu.org/licenses/>.


import argparse
from ConfigParser import SafeConfigParser
import os
import sys

import koji


# FIXME: This is pretty disgusting
class Object(object): pass
kojicli_options = Object()
kojicli_options.poll_interval = 1
kojicli = {"__name__": "anything but __main__", "options": kojicli_options}
execfile("/usr/bin/koji", kojicli)
watch_tasks = kojicli["watch_tasks"]


DEFAULT_KOJI_CONFIG = "/etc/koji.conf"


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--config", default=DEFAULT_KOJI_CONFIG,
                        help=("The koji configuration file (default: %s)"
                              % DEFAULT_KOJI_CONFIG))
    parser.add_argument("--background", action="store_true", default=False,
                        help="Run the build at a lower priority")
    parser.add_argument("--nowait", action="store_false", dest="wait",
                        default=True, help="Don't wait on the mash task")

    return parser.parse_args()

def get_config(config_file):
    config = SafeConfigParser()
    config.read(config_file)

    # These options are often specified with a '~'
    for opt in ("cert", "ca", "serverca"):
        config.set("koji", opt, os.path.expanduser(config.get("koji", opt)))

    return config

def main(opts, args):
    session = koji.ClientSession(opts.get("koji", "server"))

    # TODO: Handle other authentication methods
    session.ssl_login(opts.get("koji", "cert"), opts.get("koji", "ca"),
                      opts.get("koji", "serverca"))

    # TODO: Get the mash target
    mash_target = "nb5.0-free"
    # TODO: Get the build tag
    build_tag = "nb5.0-free-build"
    # TODO: Get the mash options
    mash_opts = {}

    priority = 5 if args.background else None

    task_id = session.mash_tree(mash_target, build_tag, mash_opts, priority)

    print("Created task: %d" % task_id)
    print("Task info: %s/taskinfo?taskID=%d" % (opts.get("koji", "weburl"),
                                                task_id))

    if args.wait:
        session.logout()
        return watch_tasks(session, [task_id])


if __name__ == "__main__":
    args = parse_args()
    opts = get_config(args.config)

    try:
        main(opts, args)

    except Exception as e:
        sys.stderr.write("Could not mash: %s\n" % e)
        sys.exit(1)

    sys.exit(0)
